# Generated by Django 2.2.4 on 2020-11-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_auto_20201103_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
