# Generated by Django 2.2.4 on 2020-11-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0003_auto_20201103_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
