# Generated by Django 2.2.4 on 2020-11-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0005_auto_20201103_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
