# Generated by Django 2.2.4 on 2020-11-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0006_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(),
        ),
    ]
