# Generated by Django 2.2.4 on 2020-11-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0007_auto_20201104_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
