# Generated by Django 2.2.4 on 2020-11-04 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0008_auto_20201104_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.CharField(default=uuid.UUID('08f75e78-1eb9-11eb-b5aa-b1b002d0b06d'), max_length=255),
        ),
    ]
