# Generated by Django 2.2.4 on 2020-11-07 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='ea', max_length=255),
        ),
    ]
